dist: xenial
language: python

matrix:
  allow_failures:
  - python: nightly
  - python: pypy
  - python: pypy3
  - python: 3.8-dev
  include:
  - python: 3.7
  - python: 3.6
  - python: 3.5
  - python: 3.4
  - python: 2.7
  - python: pypy
  - python: pypy3
  - python: 3.8-dev
  - python: nightly
  - language: java
    jdk: openjdk8
  - language: java
    jdk: openjdk11

before_script:
- if [ $TRAVIS_LANGUAGE == python ]; then pip install . pytest; fi

script:
- case $TRAVIS_LANGUAGE in
  java) mvn test ;;
  python) py.test -v --tb=native python/tests ;;
  esac
